### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by KyleMaas** [meshtastic/device-ui#1]
This looks like a fantastic improvement for the T-Deck!  How do I build the X11 version so I can help with development?

**Comment by KyleMaas** [comment]
This is marked as completed, so can you help me find where it is?

**Comment by joyel24** [comment]
@KyleMaas I hope you found your answer until that time...

It's already included as a submodule of meshtastic firmware. Clone the tft-gui-work branch and build it, it's a part of it.
